USE [master]
GO

/****** Object:  Database [StockExp]    Script Date: 03/12/2017 17:33:14 ******/
CREATE DATABASE [StockExp] ON  PRIMARY 
( NAME = N'StockExp', FILENAME = N'E:\Data\StockExp.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'StockExp_log', FILENAME = N'E:\Data\StockExp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StockExp] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockExp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockExp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StockExp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StockExp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StockExp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StockExp] SET ARITHABORT OFF 
GO

ALTER DATABASE [StockExp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StockExp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [StockExp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StockExp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StockExp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StockExp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StockExp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StockExp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StockExp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StockExp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StockExp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StockExp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StockExp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StockExp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StockExp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StockExp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StockExp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StockExp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StockExp] SET  READ_WRITE 
GO

ALTER DATABASE [StockExp] SET RECOVERY FULL 
GO

ALTER DATABASE [StockExp] SET  MULTI_USER 
GO

ALTER DATABASE [StockExp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StockExp] SET DB_CHAINING OFF 
GO


